{
 "title": "gRPC / Server",
 "description": "Common visualisations of gRPC (Golang) Server metrics",
 "tags": [
  "grpc",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(grpc_server_started_total, grpc_service)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(grpc_server_started_total{grpc_service=~\"$service\"}, grpc_method)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(grpc_server_started_total{grpc_service=~\"$service\", grpc_method=~\"$method\"}, grpc_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests started [1m]",
   "type": "timeseries",
   "description": "Rate of gRPC requests started",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_started_total{grpc_service=~\"$service\", grpc_method=~\"$method\", grpc_type=~\"$type\"}[1m])) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Requests completed [1m]",
   "type": "timeseries",
   "description": "Rate of requests completed, by status",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_service=~\"$service\", grpc_method=~\"$method\", grpc_type=~\"$type\"}[1m])) by (grpc_service, grpc_method, grpc_code)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request errors [1m]",
   "type": "timeseries",
   "description": "Rate of errors, by status",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_service=~\"$service\", grpc_method=~\"$method\", grpc_code!=\"OK\", grpc_type=~\"$type\"}[1m])) by (grpc_service, grpc_method, grpc_code)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "99th percentile response latency [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=~\"$service\", grpc_method=~\"$method\", grpc_type=\"unary\"}[5m])) by (grpc_service, grpc_method, le)\n)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  { "title": "Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Server messages received [1m]",
   "type": "timeseries",
   "description": "Rate of messages received by server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_msg_received_total{grpc_service=~\"$service\", grpc_method=~\"$method\", grpc_type=~\"$type\"}[1m])) by (grpc_service, grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server messages sent [1m]",
   "type": "timeseries",
   "description": "Rate of messages sent by server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_msg_sent_total{grpc_service=~\"$service\", grpc_method=~\"$method\", grpc_type=~\"$type\"}[1m])) by (grpc_service, grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}