{
 "title": "Prometheus Gin",
 "tags": [ "Service" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(gin_http_request_count_total, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(gin_http_request_count_total{path!~\"/metrics\", status!=\"404\", job=~\"$job\"}, path)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(gin_http_request_count_total, method)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(gin_http_request_count_total, status)"
    }
   },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Service last updated",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - gin_uptime{job=~\"$job\"}) * 1000"
    }
   ]
  },
  {
   "title": "Requests QPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gin_http_request_count_total{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ path }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "gin_uptime{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Request size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(gin_http_request_size_bytes_sum{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(gin_http_request_size_bytes_count{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ path }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Response size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(gin_http_response_size_bytes_sum{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(gin_http_response_size_bytes_count{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ path }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(gin_http_request_duration_seconds_bucket{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])) by (le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(gin_http_request_duration_seconds_sum{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])\r\n/\r\nrate(gin_http_request_duration_seconds_count{job=~\"$job\", path=~\"$path\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ path }}-{{method}}-{{status}}"
    }
   ]
  }
 ]
}